set_property PACKAGE_PIN W7 [get_ports M_clk]
set_property IOSTANDARD LVCMOS33 [get_ports M_clk]

set_property IOSTANDARD LVCMOS33 [get_ports D_in_1]
set_property IOSTANDARD LVCMOS33 [get_ports D_in_2]
set_property IOSTANDARD LVCMOS33 [get_ports D_in_3]
set_property IOSTANDARD LVCMOS33 [get_ports D_in_4]
set_property PACKAGE_PIN W5 [get_ports D_in_1]
set_property PACKAGE_PIN W6 [get_ports D_in_2]
set_property PACKAGE_PIN V4 [get_ports D_in_3]
set_property PACKAGE_PIN V5 [get_ports D_in_4]

set_property PACKAGE_PIN AA19 [get_ports H_SYNC]
set_property PACKAGE_PIN Y19  [get_ports V_SYNC]
set_property IOSTANDARD LVCMOS33 [get_ports H_SYNC]
set_property IOSTANDARD LVCMOS33 [get_ports V_SYNC]

set_property PACKAGE_PIN Y21  [get_ports VGA[0]]
set_property PACKAGE_PIN Y20  [get_ports VGA[1]]
set_property PACKAGE_PIN AB20 [get_ports VGA[2]]
set_property PACKAGE_PIN AB19 [get_ports VGA[3]]
set_property PACKAGE_PIN AB22 [get_ports VGA[4]]
set_property PACKAGE_PIN AA22 [get_ports VGA[5]]
set_property PACKAGE_PIN AB21 [get_ports VGA[6]]
set_property PACKAGE_PIN AA21 [get_ports VGA[7]]
set_property PACKAGE_PIN V20  [get_ports VGA[8]]
set_property PACKAGE_PIN U20  [get_ports VGA[9]]
set_property PACKAGE_PIN V19  [get_ports VGA[10]]
set_property PACKAGE_PIN V18  [get_ports VGA[11]]
set_property IOSTANDARD LVCMOS33 [get_ports VGA[0]]
set_property IOSTANDARD LVCMOS33 [get_ports VGA[1]]
set_property IOSTANDARD LVCMOS33 [get_ports VGA[2]]
set_property IOSTANDARD LVCMOS33 [get_ports VGA[3]]
set_property IOSTANDARD LVCMOS33 [get_ports VGA[4]]
set_property IOSTANDARD LVCMOS33 [get_ports VGA[5]]
set_property IOSTANDARD LVCMOS33 [get_ports VGA[6]]
set_property IOSTANDARD LVCMOS33 [get_ports VGA[7]]
set_property IOSTANDARD LVCMOS33 [get_ports VGA[8]]
set_property IOSTANDARD LVCMOS33 [get_ports VGA[9]]
set_property IOSTANDARD LVCMOS33 [get_ports VGA[10]]
set_property IOSTANDARD LVCMOS33 [get_ports VGA[11]]

set_property PACKAGE_PIN F22  [get_ports SEL0]
set_property IOSTANDARD LVCMOS33 [get_ports SEL0]

set_property PACKAGE_PIN T22  [get_ports LD0]
set_property IOSTANDARD LVCMOS33 [get_ports LD0]
